### Importing Libraries

In [1]:
import pandas as pd

### Data Loading and Initial Exploration

In [2]:
df_nov = pd.read_csv(r"C:\Users\ragha\OneDrive\Desktop\Projects\Cart Abondenment Analysis\2019-Nov.csv")

In [4]:
df_nov.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:00:00 UTC,view,1003461,2053013555631882655,electronics.smartphone,xiaomi,489.07,520088904,4d3b30da-a5e4-49df-b1a8-ba5943f1dd33
1,2019-11-01 00:00:00 UTC,view,5000088,2053013566100866035,appliances.sewing_machine,janome,293.65,530496790,8e5f4f83-366c-4f70-860e-ca7417414283
2,2019-11-01 00:00:01 UTC,view,17302664,2053013553853497655,NaN,creed,28.31,561587266,755422e7-9040-477b-9bd2-6a6e8fd97387
3,2019-11-01 00:00:01 UTC,view,3601530,2053013563810775923,appliances.kitchen.washer,lg,712.87,518085591,3bfb58cd-7892-48cc-8020-2f17e6de6e7f
4,2019-11-01 00:00:01 UTC,view,1004775,2053013555631882655,electronics.smartphone,xiaomi,183.27,558856683,313628f1-68b8-460d-84f6-cec7a8796ef2

In [5]:
df_nov.shape

(67501979, 9)

In [6]:
df_nov.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67501979 entries, 0 to 67501978
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 4.5+ GB

In [7]:
# Inspect event_type
df_nov['event_type'].value_counts()

event_type
view        63556110
cart         3028930
purchase      916939
Name: count, dtype: int64

In [8]:
# Inspect missing values
df_nov.isna().sum()

event_time              0
event_type              0
product_id              0
category_id             0
category_code    21898171
brand             9224078
price                   0
user_id                 0
user_session           10
dtype: int64

In [9]:
# Inspect duplicates
df_nov.duplicated().sum()

np.int64(100519)

In [19]:
df_nov['user_session'].nunique()

13776050

In [17]:
df_nov.groupby('event_type')['user_session'].nunique()

event_type
cart         1743342
purchase      773214
view        13766768
Name: user_session, dtype: int64

### Data Cleaning & Preparation

In [11]:
df_nov[df_nov['user_session'].isna()]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
14771091,2019-11-09 15:32:27 UTC,cart,19700004,2053013559104766575,NaN,kabrita,37.77,539704497,NaN
14991783,2019-11-09 17:15:24 UTC,cart,1005083,2053013555631882655,electronics.smartphone,honor,566.27,568843390,NaN
21436266,2019-11-13 04:02:03 UTC,cart,4804008,2053013554658804075,electronics.audio.headphone,bluedio,97.81,570411102,NaN
21765703,2019-11-13 07:18:35 UTC,cart,1004767,2053013555631882655,electronics.smartphone,samsung,243.51,570878749,NaN
55027396,2019-11-23 12:53:50 UTC,cart,7600528,2053013552821698803,NaN,tp-link,16.73,575357602,NaN
57521839,2019-11-25 05:04:42 UTC,cart,1802104,2053013554415534427,electronics.video.tv,arg,360.09,573722572,NaN
57690742,2019-11-25 07:03:38 UTC,cart,21403753,2053013561579406073,electronics.clocks,NaN,181.47,576301354,NaN
59356970,2019-11-26 07:48:12 UTC,cart,4804718,2053013554658804075,electronics.audio.headphone,apple,334.58,576935861,NaN
60920894,2019-11-27 07:02:20 UTC,cart,12719553,2053013553559896355,NaN,NaN,55.60,577167045,NaN
65449633,2019-11-29 17:25:56 UTC,cart,1005116,2053013555631882655,electronics.smartphone,apple,1001.42,579123407,NaN

In [12]:
# Remove missing values of user_sessions
df_nov = df_nov.dropna(subset = ['user_session'])
df_nov['user_session'].isna().sum()

np.int64(0)

In [13]:
# Inspect duplicates
df_nov.duplicated().sum()

np.int64(100519)

In [14]:
df_nov[df_nov.duplicated(keep = False)].sort_values(by = ['user_session', 'event_time']).head(10)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
27035118,2019-11-15 03:26:05 UTC,cart,1004768,2053013555631882655,electronics.smartphone,samsung,236.94,571669156,00029e5b-8868-4e59-9171-93c74c1853d3
27035120,2019-11-15 03:26:05 UTC,cart,1004768,2053013555631882655,electronics.smartphone,samsung,236.94,571669156,00029e5b-8868-4e59-9171-93c74c1853d3
27035122,2019-11-15 03:26:05 UTC,cart,1004768,2053013555631882655,electronics.smartphone,samsung,236.94,571669156,00029e5b-8868-4e59-9171-93c74c1853d3
52674583,2019-11-22 02:43:57 UTC,cart,3801134,2053013566176363511,appliances.iron,elenberg,16.71,573267101,0004ca93-1bcd-4a8d-b027-70bc68f0315d
52674585,2019-11-22 02:43:57 UTC,cart,3801134,2053013566176363511,appliances.iron,elenberg,16.71,573267101,0004ca93-1bcd-4a8d-b027-70bc68f0315d
45111435,2019-11-17 17:40:26 UTC,cart,3300317,2053013555355058573,NaN,vitek,38.33,566666495,0005cdf0-d704-448d-a359-97752c2261fc
45111444,2019-11-17 17:40:26 UTC,cart,3300317,2053013555355058573,NaN,vitek,38.33,566666495,0005cdf0-d704-448d-a359-97752c2261fc
34274021,2019-11-16 07:03:15 UTC,cart,12700975,2053013553559896355,NaN,nokian,55.86,547711541,000b893b-b969-47fb-845b-4c8842625fa2
34274025,2019-11-16 07:03:15 UTC,cart,12700975,2053013553559896355,NaN,nokian,55.86,547711541,000b893b-b969-47fb-845b-4c8842625fa2
16023678,2019-11-10 09:29:26 UTC,cart,16200315,2053013556344914381,kids.fmcg.diapers,huggies,17.50,516074959,000bf054-8945-4c32-a116-21ca012b87bc

In [15]:
# Drop duplicates
df_nov = df_nov.drop_duplicates()

In [16]:
# Convert dtype of event_time to datetime
df_nov['event_time'] = pd.to_datetime(df_nov['event_time'])
df_nov['event_time'].dtype

datetime64[ns, UTC]

In [17]:
# Inspect category_code column
df_nov['category_code'].dropna().str.split('.').str.len().value_counts().sort_index()

category_code
2    26738499
3    18728273
4       63258
Name: count, dtype: int64

In [18]:
# Inspect category_code's 4 parts rows unique values
df_nov[df_nov['category_code'].str.count(r'\.') == 3]['category_code'].nunique()

1

In [19]:
## Create columns main_category, sub_category and product_type
parts = df_nov['category_code'].str.split('.')

df_nov['main_category'] = parts.str[0]
df_nov['sub_category'] = parts.where(parts.str.len() == 3).str[1]
df_nov['product_type'] = parts.str[-1]

In [20]:
# Fill missing values with Unknown
df_nov.loc[df_nov['category_code'].isna(), 'category_code'] = 'Unknown'
df_nov.loc[df_nov['brand'].isna(), 'brand'] = 'Unknown'
df_nov.loc[df_nov['main_category'].isna(), 'main_category'] = 'Unknown'
df_nov.loc[df_nov['sub_category'].isna(), 'sub_category'] = 'Unknown'
df_nov.loc[df_nov['product_type'].isna(), 'product_type'] = 'Unknown'

In [21]:
df_nov[['category_code','brand', 'main_category', 'sub_category', 'product_type']].head(10)

,category_code,brand,main_category,sub_category,product_type
0,electronics.smartphone,xiaomi,electronics,Unknown,smartphone
1,appliances.sewing_machine,janome,appliances,Unknown,sewing_machine
2,Unknown,creed,Unknown,Unknown,Unknown
3,appliances.kitchen.washer,lg,appliances,kitchen,washer
4,electronics.smartphone,xiaomi,electronics,Unknown,smartphone
5,computers.notebook,hp,computers,Unknown,notebook
6,computers.notebook,hp,computers,Unknown,notebook
7,Unknown,rondell,Unknown,Unknown,Unknown
8,Unknown,michelin,Unknown,Unknown,Unknown
9,electronics.smartphone,apple,electronics,Unknown,smartphone

In [22]:
df_nov.info()

<class 'pandas.core.frame.DataFrame'>
Index: 67401450 entries, 0 to 67501978
Data columns (total 12 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     datetime64[ns, UTC]
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
 9   main_category  object
 10  sub_category   object
 11  product_type   object
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(7)
memory usage: 6.5+ GB

In [23]:
# Inspect price column
df_nov['price'].describe()

count    6.740145e+07
mean     2.924819e+02
std      3.557358e+02
min      0.000000e+00
25%      6.924000e+01
50%      1.657700e+02
75%      3.603400e+02
max      2.574070e+03
Name: price, dtype: float64

In [24]:
# Inspect num of zero values
(df_nov['price'] == 0).sum()

np.int64(187987)

In [25]:
df_nov.loc[df_nov['price'].eq(0), 'event_type'].value_counts()

event_type
view    183678
cart      4309
Name: count, dtype: int64

In [26]:
# Save november month cleaned data
df_nov.to_parquet(r"C:\Users\ragha\OneDrive\Desktop\Projects\Cart Abondenment Analysis\2019-Nov-cleaned.parquet", index = False)

In [3]:
df_nov = pd.read_parquet(r"C:\Users\ragha\OneDrive\Desktop\Projects\Cart Abondenment Analysis\2019-Nov-cleaned.parquet")

In [13]:
from sqlalchemy import create_engine
import pymysql

In [14]:
# MySQL Connection

username = 'root'
password = '1234567890'
host = 'localhost'
port = '3306'
database = 'cart_abandonment'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

In [15]:
# Connection test
engine.connect()

In [16]:
# Loading dataset to MySQL
df_nov.to_sql('ecommerce_events', engine, if_exists = 'append', index = False, chunksize = 100000)

67401450